// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giktzrxatpqkltacdzai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpa3R6cnhhdHBxa2x0YWNkemFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMzM4ODUsImV4cCI6MjA3NjYwOTg4NX0.tQ5yHC88NdfQ92U6pZ8spjmgNwKGzYAHJKsJXs9x0KU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});